<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261004185044 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, entity VARCHAR(255) NOT NULL, entity_id VARCHAR(255) NOT NULL, previous JSON NOT NULL, changes JSON NOT NULL, note VARCHAR(255) DEFAULT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8F3F68C5A76ED395 ON log (user_id)');
        $this->addSql('CREATE INDEX idx_log_entity ON log (entity, entity_id)');
        $this->addSql('CREATE TABLE log_deleted_data (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, entity VARCHAR(255) NOT NULL, entity_id VARCHAR(255) NOT NULL, note VARCHAR(255) DEFAULT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2079DCD0A76ED395 ON log_deleted_data (user_id)');
        $this->addSql('CREATE INDEX idx_log_deleted_data_entity ON log_deleted_data (entity, entity_id)');
        $this->addSql('CREATE TABLE log_today (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, entity VARCHAR(255) NOT NULL, entity_id VARCHAR(255) NOT NULL, previous JSON NOT NULL, changes JSON NOT NULL, note VARCHAR(255) DEFAULT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_93AA4D98A76ED395 ON log_today (user_id)');
        $this->addSql('CREATE INDEX idx_log_today_entity ON log_today (entity, entity_id)');
        $this->addSql('ALTER TABLE log ADD CONSTRAINT FK_8F3F68C5A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE log_deleted_data ADD CONSTRAINT FK_2079DCD0A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE log_today ADD CONSTRAINT FK_93AA4D98A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE log DROP CONSTRAINT FK_8F3F68C5A76ED395');
        $this->addSql('ALTER TABLE log_deleted_data DROP CONSTRAINT FK_2079DCD0A76ED395');
        $this->addSql('ALTER TABLE log_today DROP CONSTRAINT FK_93AA4D98A76ED395');
        $this->addSql('DROP TABLE log');
        $this->addSql('DROP TABLE log_deleted_data');
        $this->addSql('DROP TABLE log_today');
    }
}
