server {
    listen 80;
    server_name localhost;

    # Przekierowanie ruchu API, Profilera i Web Debug Toolbara do Symfony
    location ~ ^/(api|_profiler|_wdt) {
        root /var/www/backend/public;
        try_files $uri /index.php$is_args$args;
    }

    # Obsługa PHP dla Symfony
    location ~ ^/index\.php(/|$) {
        root /var/www/backend/public;
        fastcgi_pass php:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $document_root;
        internal;
    }

    # Zabezpieczenie innych plików PHP
    location ~ \.php$ {
        return 404;
    }

    # Przekierowanie pozostałego ruchu do deweloperskiego serwera Angulara
    location / {
        proxy_pass http://frontend:4200;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}